// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: prodvana/common_config/retry.proto

package common_config

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Notification with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Notification) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Notification with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NotificationMultiError, or
// nil if none found.
func (m *Notification) ValidateAll() error {
	return m.validate(true)
}

func (m *Notification) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetConfigOverride()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, NotificationValidationError{
					field:  "ConfigOverride",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, NotificationValidationError{
					field:  "ConfigOverride",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConfigOverride()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return NotificationValidationError{
				field:  "ConfigOverride",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if utf8.RuneCountInString(m.GetMessage()) < 1 {
		err := NotificationValidationError{
			field:  "Message",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return NotificationMultiError(errors)
	}

	return nil
}

// NotificationMultiError is an error wrapping multiple validation errors
// returned by Notification.ValidateAll() if the designated constraints aren't met.
type NotificationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NotificationMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NotificationMultiError) AllErrors() []error { return m }

// NotificationValidationError is the validation error returned by
// Notification.Validate if the designated constraints aren't met.
type NotificationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NotificationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NotificationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NotificationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NotificationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NotificationValidationError) ErrorName() string { return "NotificationValidationError" }

// Error satisfies the builtin error interface
func (e NotificationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNotification.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NotificationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NotificationValidationError{}

// Validate checks the field values on RetryConfig with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RetryConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RetryConfig with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RetryConfigMultiError, or
// nil if none found.
func (m *RetryConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *RetryConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetFirstFailureNotification()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RetryConfigValidationError{
					field:  "FirstFailureNotification",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RetryConfigValidationError{
					field:  "FirstFailureNotification",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFirstFailureNotification()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RetryConfigValidationError{
				field:  "FirstFailureNotification",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	oneofLimitPresent := false
	switch v := m.Limit.(type) {
	case *RetryConfig_MaxRetryDuration:
		if v == nil {
			err := RetryConfigValidationError{
				field:  "Limit",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofLimitPresent = true

		if d := m.GetMaxRetryDuration(); d != nil {
			dur, err := d.AsDuration(), d.CheckValid()
			if err != nil {
				err = RetryConfigValidationError{
					field:  "MaxRetryDuration",
					reason: "value is not a valid duration",
					cause:  err,
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			} else {

				gt := time.Duration(0*time.Second + 0*time.Nanosecond)

				if dur <= gt {
					err := RetryConfigValidationError{
						field:  "MaxRetryDuration",
						reason: "value must be greater than 0s",
					}
					if !all {
						return err
					}
					errors = append(errors, err)
				}

			}
		}

	case *RetryConfig_RetryForever:
		if v == nil {
			err := RetryConfigValidationError{
				field:  "Limit",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofLimitPresent = true
		// no validation rules for RetryForever
	default:
		_ = v // ensures v is used
	}
	if !oneofLimitPresent {
		err := RetryConfigValidationError{
			field:  "Limit",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RetryConfigMultiError(errors)
	}

	return nil
}

// RetryConfigMultiError is an error wrapping multiple validation errors
// returned by RetryConfig.ValidateAll() if the designated constraints aren't met.
type RetryConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RetryConfigMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RetryConfigMultiError) AllErrors() []error { return m }

// RetryConfigValidationError is the validation error returned by
// RetryConfig.Validate if the designated constraints aren't met.
type RetryConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RetryConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RetryConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RetryConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RetryConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RetryConfigValidationError) ErrorName() string { return "RetryConfigValidationError" }

// Error satisfies the builtin error interface
func (e RetryConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRetryConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RetryConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RetryConfigValidationError{}
